version: "3"
services:
  lab:
    container_name: test
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"

    volumes:
      - .:/workdir
    command: start.sh jupyter lab
